data_path: /home/bobododo/GNC/MSF/chapter2/catkin_ws/src/lidar_localization   # 数据存放路径

# 匹配
# TODO: implement your custom registration method and add it here
registration_method: ICP_MANUAL   # 选择点云匹配方法，目前支持：ICP, NDT,新增ICP_MANUAL

# 局部地图
key_frame_distance: 2.0 # 关键帧距离
local_frame_num: 50
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter

# rviz显示
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

# 各配置选项对应参数
## 匹配相关参数
ICP:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 30
NDT:
    res : 1.0
    step_size : 0.1
    trans_eps : 0.01
    max_iter : 30
ICP_SVD:
    max_corr_dist : 1.2
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 10
ICP_MANUAL:
    max_correspondence_distance:  1.0
    max_iter:    30
## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.3, 0.3, 0.3]
    frame:
        leaf_size: [1.3, 1.3, 1.3]
    display:
        leaf_size: [0.5, 0.5, 0.5]
